### ISSUE TITLE
auto parry

### ISSUE THREAD

**Issue by lollikechebureks** [Saniee/ULTRAKILLTrainer#1]
would be good if you be able to auto parry any projectiles or parryable attacks

**Comment by Saniee** [comment]
Hey, sorry to respond so late. I don't think this is possible with the current way parrying is handled as I can see.

**Comment by Saniee** [comment]
I will be looking at this more closely, since the change to cheat engine opened more ways of doing things, but keep in mind I have my own free time. And I don't always choose to update this trainer while having it.
