### ISSUE TITLE
Nailgun ammo

### ISSUE THREAD

**Issue by AdfasdfasGD** [Saniee/ULTRAKILLTrainer#2]
Nailgun ammo doesnt work on ALT version

**Comment by Saniee** [comment]
Handling of ammo in ULTRAKILL is a bit weird then normal games. I will look into making a better version of this-- soon-ish. To make it easier to release updates however I will most likely switch to Cheat Engine Tables, so I can also make custom scripts and implement something like an auto parry etc.
